name:                typedlua-build-composer
version:             0.1

dependencies:
- base >= 4.7 && < 5
- directory
- process
- typed-process
- split
- bytestring

default-extensions:
- OverloadedStrings
- LambdaCase

ghc-options:
- -Wall

library:
  source-dirs: src

executables:
  typedlua-build-composer-exe:
    main:                Main.hs
    source-dirs:         tlc-composer
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - typedlua-build-composer
